<html>
  <body>
    <p>O Mini Pig é um conjunto de scripts para conversão de arquivos de vídeo para edição no Davinci Resolve da <a href="https://www.blackmagicdesign.com/br">Blackmagick</a>.
    <p>O software suporta um número limitado de formatos.</p>
    <p>Para mais informações sobre o script, acesso o repositório no GitHub: <a href="#">https://gitlab.com/rtomkiel/minipig</a>  ."</p>
    <br>
    <br>
    <p>Selecione um vídeo para conversão e utilização no Davinici Resolve for GNU/Linux</p>
  <body>
<html>
